import type {
  Conversation,
  HermesJob,
  SystemSource,
  WorkspaceFile,
} from "@/contracts/cockpit";

export const mockSystemSources: SystemSource[] = [
  {
    id: "prompt",
    title: "System Prompt",
    category: "Prompt snapshot",
    summary: "The prompt snapshot used by the latest eligible conversation.",
    content:
      "You are Hermes, a local-first assistant. Observe the active workspace, follow repository instructions, and keep durable context separate from transient conversation state.\n\nThis is synthetic fixture content. Real prompt text remains server-side until the read-only adapter is enabled.",
    stamp: {
      id: "system-prompt",
      label: "Session database",
      path: "<CONVERSATION_STORE> / <PROMPT_RECORDS>",
      observedAt: "2026-08-28T02:42:00+08:00",
      state: "ready",
    },
    metadata: [
      { label: "Used by", value: "Cockpit planning review" },
      { label: "Session time", value: "2026-08-28 02:42 CST", mono: true },
      { label: "Fingerprint", value: "a81c42…", mono: true },
      { label: "Preview", value: "Synthetic fixture" },
    ],
  },
  {
    id: "memory",
    title: "Memory",
    category: "Durable context",
    summary: "Long-lived context retained by Hermes.",
    content:
      "# Memory\n\n- Prefer local-first tools when an authoritative local source exists.\n- Keep observability separate from control.\n- Make source provenance visible when presenting system state.",
    stamp: {
      id: "memory",
      label: "Hermes memory",
      path: "<MEMORY_SOURCE>",
      observedAt: "2026-08-28T02:38:00+08:00",
      state: "ready",
    },
    metadata: [
      { label: "Type", value: "Markdown" },
      { label: "Size", value: "2.6 KB", mono: true },
      { label: "Modified", value: "2026-08-22 15:51 CST", mono: true },
      { label: "Preview", value: "Available" },
    ],
  },
  {
    id: "user",
    title: "User Profile",
    category: "Durable context",
    summary: "User preferences and stable profile context.",
    content:
      "# User Profile\n\n- Values concise explanations backed by direct evidence.\n- Works primarily in Asia/Shanghai.\n- Prefers explicit boundaries before an agent mutates durable state.",
    stamp: {
      id: "user-profile",
      label: "Hermes memory",
      path: "<USER_PROFILE_SOURCE>",
      observedAt: "2026-08-28T02:38:00+08:00",
      state: "ready",
    },
    metadata: [
      { label: "Type", value: "Markdown" },
      { label: "Size", value: "2.3 KB", mono: true },
      { label: "Modified", value: "2026-08-25 11:48 CST", mono: true },
      { label: "Preview", value: "Available" },
    ],
  },
  {
    id: "soul",
    title: "SOUL.md",
    category: "Operating principles",
    summary: "High-level principles shaping Hermes behavior.",
    content:
      "# Operating Principles\n\nBe direct, curious, and useful. Respect boundaries around private data. Prefer reversible actions and make uncertainty visible.",
    stamp: {
      id: "soul",
      label: "Approved workspace",
      path: "SOUL.md",
      observedAt: "2026-08-28T02:37:00+08:00",
      state: "ready",
    },
    metadata: [
      { label: "Type", value: "Markdown" },
      { label: "Size", value: "1.2 KB", mono: true },
      { label: "Modified", value: "2026-06-10 18:52 CST", mono: true },
      { label: "Preview", value: "Available" },
    ],
  },
  {
    id: "agents",
    title: "AGENTS.md",
    category: "Repository rules",
    summary: "Instructions applied inside the approved workspace.",
    content:
      "# Repository Instructions\n\nUse repository-local conventions, verify changes, and keep local server startup commands explicit. Do not hide a failed localhost bind behind background services.",
    stamp: {
      id: "agents",
      label: "Approved workspace",
      path: "AGENTS.md",
      observedAt: "2026-08-28T02:37:00+08:00",
      state: "ready",
    },
    metadata: [
      { label: "Type", value: "Markdown" },
      { label: "Size", value: "6.4 KB", mono: true },
      { label: "Modified", value: "2026-08-24 09:53 CST", mono: true },
      { label: "Preview", value: "Available" },
    ],
  },
  {
    id: "skills",
    title: "Skills",
    category: "Capabilities",
    summary: "Installed skill manifests visible to Hermes.",
    content:
      "42 synthetic manifests discovered\n\nresearch / 8\nsoftware-development / 9\nproductivity / 7\nmedia / 5\ndomain / 4\nother categories / 9\n\nManifest bodies load only when selected.",
    stamp: {
      id: "skills",
      label: "Hermes skills",
      path: "<SKILL_MANIFEST_SOURCES>",
      observedAt: "2026-08-28T02:36:00+08:00",
      state: "ready",
      truncated: true,
    },
    metadata: [
      { label: "Manifests", value: "42 synthetic", mono: true },
      { label: "Archives", value: "Excluded" },
      { label: "Fixture", value: "Synthetic summary" },
    ],
    collection: {
      kind: "skills",
      items: [
        {
          id: "skill-111111111111111111111111",
          name: "research-brief",
          description: "Builds a bounded research brief from approved sources.",
          category: "research",
          status: "enabled",
          path: "research/research-brief/SKILL.md",
          previewable: true,
        },
        {
          id: "skill-222222222222222222222222",
          name: "document-export",
          description: "Creates document artifacts from prepared content.",
          category: "productivity",
          status: "disabled",
          path: "productivity/document-export/SKILL.md",
          previewable: true,
        },
      ],
    },
  },
  {
    id: "tools",
    title: "Tools",
    category: "Capabilities",
    summary: "Effective Hermes toolsets for the active profile.",
    content:
      "Enabled toolsets\n\nterminal\nweb\nmemory\nfiles\nbrowser\nmedia\n\nDisabled and implementation-only modules are not presented as active tools.",
    stamp: {
      id: "tools",
      label: "Hermes config",
      path: "<SAFE_CONFIG_SOURCE> / toolsets",
      observedAt: "2026-08-28T02:36:00+08:00",
      state: "ready",
    },
    metadata: [
      { label: "Platform", value: "CLI" },
      { label: "Enabled", value: "6 fixture rows", mono: true },
      { label: "Source", value: "Allowlisted config" },
      { label: "Secrets", value: "Omitted" },
    ],
    collection: {
      kind: "tools",
      items: [
        {
          id: "toolset-file",
          name: "file",
          description: "Enabled by platform_toolsets.cli.",
          category: "Built-in",
          status: "enabled",
        },
        {
          id: "toolset-vision",
          name: "vision",
          description: "Known to Hermes but not enabled in platform_toolsets.cli.",
          category: "Built-in",
          status: "disabled",
        },
      ],
    },
  },
  {
    id: "providers",
    title: "Providers",
    category: "Model routing",
    summary: "Safe model and provider identifiers only.",
    content:
      "Active provider\nlocal fixture provider\n\nActive model\ngpt-fixture\n\nCredentials, endpoints, headers, and environment references are omitted.",
    stamp: {
      id: "providers",
      label: "Hermes config",
      path: "<SAFE_CONFIG_SOURCE> / model",
      observedAt: "2026-08-28T02:36:00+08:00",
      state: "ready",
    },
    metadata: [
      { label: "Provider", value: "fixture-provider", mono: true },
      { label: "Model", value: "gpt-fixture", mono: true },
      { label: "Credentials", value: "Not read" },
      { label: "Preview", value: "Allowlisted" },
    ],
  },
];

export const mockConversations: Conversation[] = [
  {
    id: "conv-001",
    title: "Cockpit information architecture",
    preview: "Clarified the five read-only surfaces and removed Projects.",
    source: "CLI",
    lastActivity: "2026-08-28 02:42",
    model: "gpt-fixture",
    messageCount: 18,
    toolCallCount: 2,
    profile: "default",
    workspace: "<local-path>/Hermes",
    messages: [
      {
        id: "msg-001",
        role: "user",
        content: "Help me reduce Cockpit to the smallest useful first release.",
        timestamp: "02:31",
      },
      {
        id: "msg-002",
        role: "assistant",
        content:
          "The smallest coherent release is an observability surface: Overview, System, Conversations, Files, and Jobs. It should not organize or control Hermes yet.",
        timestamp: "02:33",
      },
      {
        id: "msg-003",
        role: "tool",
        content: "Inspected local source schemas without reading message bodies.",
        timestamp: "02:35",
      },
      {
        id: "msg-004",
        role: "assistant",
        content:
          "The source inventory supports all five surfaces. A second database is unnecessary for v0.1.",
        timestamp: "02:42",
      },
    ],
  },
  {
    id: "conv-002",
    title: "Read-only boundary review",
    preview: "Defined exclusions for credentials, mutations, and remote access.",
    source: "Desktop",
    lastActivity: "2026-08-27 22:14",
    model: "gpt-fixture",
    messageCount: 12,
    toolCallCount: 0,
    profile: "default",
    workspace: "<local-path>/Hermes",
    messages: [
      {
        id: "msg-005",
        role: "user",
        content: "What should Cockpit never expose?",
        timestamp: "22:07",
      },
      {
        id: "msg-006",
        role: "assistant",
        content:
          "Credential files, raw provider configuration, hidden reasoning, job prompts, scripts, and arbitrary absolute-path reads stay outside the browser boundary.",
        timestamp: "22:14",
      },
    ],
  },
  {
    id: "conv-003",
    title: "Hermes memory cleanup notes",
    preview: "Reviewed durable context without changing memory files.",
    source: "CLI",
    lastActivity: "2026-08-27 18:09",
    model: "gpt-fixture",
    messageCount: 9,
    toolCallCount: 1,
    profile: "default",
    workspace: "<local-path>/Hermes",
    messages: [
      {
        id: "msg-007",
        role: "user",
        content: "Show me which memory areas are growing, but do not edit them.",
        timestamp: "17:56",
      },
      {
        id: "msg-008",
        role: "assistant",
        content:
          "Memory and User Profile are both available. I can show their sizes and previews while leaving cleanup for a future reviewed workflow.",
        timestamp: "18:09",
      },
    ],
  },
  {
    id: "conv-004",
    title: "Local workspace inventory",
    preview: "Mapped visible file types and preview limits.",
    source: "Desktop",
    lastActivity: "2026-08-27 15:26",
    model: "gpt-fixture",
    messageCount: 14,
    toolCallCount: 3,
    profile: "default",
    workspace: "<local-path>/Hermes",
    messages: [
      {
        id: "msg-009",
        role: "assistant",
        content:
          "The workspace contains Markdown, JSON, HTML, PDF, and Python files. Text previews can be bounded; binaries should remain metadata-only.",
        timestamp: "15:26",
      },
    ],
  },
  {
    id: "conv-005",
    title: "Background job visibility",
    preview: "Separated job definitions from execution metadata.",
    source: "CLI",
    lastActivity: "2026-08-27 12:04",
    model: "gpt-fixture",
    messageCount: 11,
    toolCallCount: 2,
    profile: "default",
    workspace: "<local-path>/Hermes",
    messages: [
      {
        id: "msg-010",
        role: "assistant",
        content:
          "Jobs should show schedules and statuses. Prompts, scripts, recipient identifiers, and control actions remain excluded.",
        timestamp: "12:04",
      },
    ],
  },
  {
    id: "conv-006",
    title: "Prompt provenance experiment",
    preview: "Compared prompt snapshots with session timestamps.",
    source: "Desktop",
    lastActivity: "2026-08-26 20:44",
    model: "gpt-fixture",
    messageCount: 16,
    toolCallCount: 1,
    profile: "default",
    workspace: "<local-path>/Hermes",
    messages: [
      {
        id: "msg-011",
        role: "assistant",
        content:
          "A prompt hash is useful only with provenance. Cockpit should label the conversation and time that made a snapshot relevant.",
        timestamp: "20:44",
      },
    ],
  },
  {
    id: "conv-007",
    title: "Interface language decision",
    preview: "Kept navigation English while preserving source-language content.",
    source: "CLI",
    lastActivity: "2026-08-26 16:18",
    model: "gpt-fixture",
    messageCount: 7,
    toolCallCount: 0,
    profile: "default",
    workspace: "<local-path>/Hermes",
    messages: [
      {
        id: "msg-012",
        role: "assistant",
        content:
          "Navigation remains Overview, System, Conversations, Files, and Jobs. Dates are local and source content is not translated.",
        timestamp: "16:18",
      },
    ],
  },
];

export const mockFiles: WorkspaceFile[] = [
  {
    id: "file-001",
    name: "AGENTS.md",
    path: "AGENTS.md",
    entryType: "file",
    kind: "Markdown",
    size: "6.4 KB",
    sizeBytes: 6_554,
    modifiedAt: "2026-08-24 09:53",
    previewState: "available",
    content:
      "# Repository Instructions\n\nWhen starting a local server, use the repository command and report the exact localhost fallback if the port cannot bind.",
  },
  {
    id: "file-002",
    name: "SOUL.md",
    path: "SOUL.md",
    entryType: "file",
    kind: "Markdown",
    size: "1.2 KB",
    sizeBytes: 1_229,
    modifiedAt: "2026-06-10 18:52",
    previewState: "available",
    content:
      "# Operating Principles\n\nBe direct, preserve user control, and make uncertainty visible.",
  },
  {
    id: "file-003",
    name: "cockpit-v0.1-requirements.md",
    path: "docs/cockpit-v0.1-requirements.md",
    entryType: "file",
    kind: "Markdown",
    size: "14.8 KB",
    sizeBytes: 15_155,
    modifiedAt: "2026-08-27 15:39",
    previewState: "available",
    content:
      "# Cockpit v0.1 Requirements\n\nCockpit is a read-only observability surface for Hermes: system context, conversations, files, and jobs.",
  },
  {
    id: "file-004",
    name: "tmp_lance_thread.pdf",
    path: "tmp_lance_thread.pdf",
    entryType: "file",
    kind: "PDF document",
    size: "284.7 KB",
    sizeBytes: 291_533,
    modifiedAt: "2026-06-12 14:28",
    previewState: "metadata-only",
  },
  {
    id: "file-005",
    name: "change-proposals.md",
    path: "change-proposals.md",
    entryType: "file",
    kind: "Markdown",
    size: "29.4 KB",
    sizeBytes: 30_106,
    modifiedAt: "2026-08-24 09:53",
    previewState: "available",
    content:
      "# Change Proposals\n\nThis fixture represents a longer workspace document. The real adapter applies server-side byte and character limits before any preview reaches the browser.",
  },
  {
    id: "file-006",
    name: "tmp_codez_substack.html",
    path: "tmp_codez_substack.html",
    entryType: "file",
    kind: "HTML source",
    size: "323.2 KB",
    sizeBytes: 330_957,
    modifiedAt: "2026-06-12 14:31",
    previewState: "metadata-only",
  },
];

export const mockJobs: HermesJob[] = [
  {
    id: "job-001",
    name: "Workspace index refresh",
    schedule: "Every day at 09:30",
    createdAt: "2026-08-01T08:15:00+08:00",
    state: "enabled",
    lastRun: "2026-08-28 09:30",
    nextRun: "2026-08-29 09:30",
    lastStatus: "success",
    failureStreak: 0,
    delivery: "Local summary",
    profile: "default",
    toolsets: ["files", "memory"],
    recordedAttempts: 18,
    executions: [
      {
        id: "exec-001",
        status: "success",
        startedAt: "2026-08-28 09:30:01",
        finishedAt: "2026-08-28 09:30:18",
      },
      {
        id: "exec-002",
        status: "success",
        startedAt: "2026-08-27 09:30:01",
        finishedAt: "2026-08-27 09:30:16",
      },
    ],
  },
  {
    id: "job-002",
    name: "Research digest",
    schedule: "Weekdays at 18:00",
    createdAt: "2026-08-02T10:30:00+08:00",
    state: "enabled",
    lastRun: "2026-08-27 18:00",
    nextRun: "2026-08-28 18:00",
    lastStatus: "failed",
    failureStreak: 1,
    delivery: "Messaging platform",
    profile: "default",
    toolsets: ["web", "research"],
    recordedAttempts: 7,
    executions: [
      {
        id: "exec-003",
        status: "failed",
        startedAt: "2026-08-27 18:00:01",
        finishedAt: "2026-08-27 18:00:09",
      },
    ],
  },
  {
    id: "job-003",
    name: "Memory review reminder",
    schedule: "Every Sunday at 20:00",
    createdAt: "2026-08-03T14:45:00+08:00",
    state: "paused",
    lastRun: "2026-08-23 20:00",
    nextRun: "Paused",
    lastStatus: "success",
    failureStreak: 0,
    delivery: "Local notification",
    profile: "default",
    toolsets: ["memory"],
    recordedAttempts: 4,
    executions: [],
  },
  {
    id: "job-004",
    name: "Knowledge base integrity",
    schedule: "Every 6 hours",
    createdAt: "2026-08-04T09:00:00+08:00",
    state: "enabled",
    lastRun: "2026-08-28 06:00",
    nextRun: "2026-08-28 12:00",
    lastStatus: "success",
    failureStreak: 0,
    delivery: "None",
    profile: "default",
    toolsets: ["files"],
    recordedAttempts: 24,
    executions: [],
  },
  {
    id: "job-005",
    name: "Weekly activity summary",
    schedule: "Friday at 17:30",
    createdAt: "2026-08-05T16:20:00+08:00",
    state: "enabled",
    lastRun: "Never",
    nextRun: "2026-08-28 17:30",
    lastStatus: "never",
    failureStreak: 0,
    delivery: "Messaging platform",
    profile: "default",
    toolsets: ["memory", "files"],
    recordedAttempts: 0,
    executions: [],
  },
];
